### PR TITLE
Allow any html tags, not just <a> and <button>, small CSS refactoring.

### PR DESCRIPTION
**Pull request by paulmillr**
The title says it all.

### CODE REVIEW

**Comment by burakerdem** [comment]
I agree with that. Mostly `<input type="submit">` is used to submit forms but it's not possible to style those submit buttons with CSS3 Buttons. **paulmillr's** implementation is what we need.

**Comment by didip** [comment]
+1 for this patch. I have the exact modification and it works great for input type="submit".

**Comment by paulmillr** [comment]
Seems that @michenriksen no longer maintains this.
I've switched some time ago to [fork of this repo](https://github.com/necolas/css3-github-buttons), it seems to be better one and that repo already has my idea. I propose to do the same to other guys.

**Comment by didip** [comment]
@paulmillr Thanks for the pointer. The fork looks great. It no longer use image sprites. Awesome!

**Pull request closed without merging**
