### PR TITLE
CSS3 gradients, <button> and <input> support, and more

### PR DESCRIPTION
**Pull request by necolas**
This is more of a pointer to my fork if you're interested. I'm not sure that you'll want to pull all these commits because I've rewritten all the code.

Some of the changes include:
- The gradient backgrounds are done with CSS gradients.
- Works on any element, including `<button>`, and will work on `<input>` elements (although the icons won't).
- Uses pseudo-elements to display the icons, thereby avoiding the need for an empty `<span>`.
- More flexible way to group buttons, and groups of groups or single buttons.
- Added styles to create the white button groups found on GitHub ("Watchers" / "Forks").
- Improved accessibility by adding :focus styles for keyboard support.

Thanks

### CODE REVIEW

**Comment by paulblyth** [comment]
I like the use of CSS3 gradients, but they look a bit too dark in comparison to the original .png. Maybe if we have the .psd source we could replicate the gradients more accurately in CSS.

*This could just be my eyes and they may be fine

**Comment by necolas** [comment]
Actually, the original .png is too light compared to the buttons on GitHub. I altered the gradients so that they are a closer approximation of the GitHub button appearance.

**Comment by paulblyth** [comment]
That's fair enough, as long as my eyes weren't playing tricks on me. Good work by the way, thanks for your efforts

**Comment by necolas** [comment]
Thanks for the feedback Paul.

**Pull request closed without merging**
